auth_enabled: false

server:
  http_listen_port: 3102
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 9095

common:
  path_prefix: /data
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /data/chunks
  boltdb_shipper:
    active_index_directory: /data/index
    cache_location: /data/cache
    cache_ttl: 24h

compactor:
  working_directory: /data/compactor

limits_config:
  retention_period: 168h
  allow_structured_metadata: false

frontend:
  scheduler_address: ""

frontend_worker:
  frontend_address: 127.0.0.1:9095
