auth_enabled: false

server:
  http_listen_port: 3102

frontend_worker:
  frontend_address: 127.0.0.1:9095

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules_storage # Lưu rules động
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Cấu hình Ingester để tránh lỗi timeout
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal

# Cấu hình Querier
querier:
  max_concurrent: 20

query_range:
  parallelise_shardable_queries: true
  cache_results: true

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_global_streams_per_user: 0
  max_streams_per_user: 0
  max_query_length: 721h
  max_query_parallelism: 32
  max_entries_limit_per_query: 10000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 168h
  allow_structured_metadata: false

schema_config:
  configs:
    # Khối cũ để đọc dữ liệu cũ
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
    # Khối mới cho dữ liệu mới, hiệu năng tốt hơn
    - from: 2025-11-11
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  rule_path: /loki/rules_storage # Đọc rules động từ API
  storage:
    type: local
    local:
      directory: /loki/rules_source # Đọc rules tĩnh từ source code
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  enable_api: true
  wal:
    dir: /loki/ruler-wal
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write
      send_exemplars: true
  alertmanager_url: ""
